# Stage 1: Build stage (to install dependencies)
FROM python:3.12-slim AS builder

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies and tools to build packages if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy only the required files to avoid unnecessary files in the image
COPY requirements.txt .

# Install the dependencies in the container
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Final stage (to copy the app and dependencies from builder)
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the installed dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

# Copy the Streamlit app to the container
COPY streamlit_sentiment_analysis /app/streamlit_sentiment_analysis

# Expose the port that Streamlit will run on
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "streamlit_sentiment_analysis/app.py"]
